group:
  - files:
    - source: python/static/
      dest: ./
    repos: |
      Glatzel/dxf2kml
      Glatzel/hippo
      Glatzel/jxws
      Glatzel/knitting
      Glatzel/ms-redeem
      Glatzel/py-bench
      Glatzel/py-glatzel
      Glatzel/vinaya
      Glatzel/watch-media
      Glatzel/xm-metro-qr
      Glatzel/zygs
  - files:
    - source: common/static/cliff.toml
      dest: cliff.toml
    repos: |
      Glatzel/hippo
      Glatzel/mason
      Glatzel/py-glatzel
      Glatzel/vinaya
