group:
  - files:
    - source: template/
      dest: ./
    repos: |
      Glatzel/G-Houdini
      Glatzel/G-Rhino
      Glatzel/knitting
      Glatzel/py-glatzel
      Glatzel/watch-media
      Glatzel/zygs
  - files:
    - source: template/ruff.toml
      dest: ruff.toml
    repos: Glatzel/xm-metro-qr