group:
  - files:
    - source: python/universal/
      dest: ./
    repos: |
      Glatzel/dxf2kml
      Glatzel/hippo
      Glatzel/jxws
      Glatzel/knitting
      Glatzel/ms-redeem
      Glatzel/py-bench
      Glatzel/py-glatzel
      Glatzel/vinaya
      Glatzel/watch-media
      Glatzel/xm-metro-qr
      Glatzel/zygs