group:
  - files:
    - source: template/
      dest: ./
    repos: |
      Glatzel/dxf2kml
      Glatzel/hippo
      Glatzel/jxws
      Glatzel/knitting
      Glatzel/py-bench-arithmetic
      Glatzel/py-bench-audio
      Glatzel/py-glatzel
      Glatzel/vinaya
      Glatzel/watch-media
      Glatzel/xm-metro-qr
      Glatzel/zygs