group:
  - files:
    - source: template/
      dest: ./
    repos: |
      Glatzel/dxf2kml
      Glatzel/G-Houdini
      Glatzel/G-Rhino
      Glatzel/jxws
      Glatzel/knitting
      Glatzel/py-glatzel
      Glatzel/xm-metro-qr
      Glatzel/watch-media
      Glatzel/zygs

  - files:
    - source: template/ruff.toml
      dest: |
        audio_load/ruff.toml
        broadcast/ruff.toml
        datumcompense/ruff.toml
        fft/ruff.toml
    - source: template/scripts/
      dest: |
        audio_load/
        broadcast/
        datumcompense/
        fft/
    repos: |
      Glatzel/G-Benchmark