group:
  - files:
    - source: template/
      dest: ./
    repos: |
      Glatzel/dxf2kml
      Glatzel/G-Benchmark
      Glatzel/G-Houdini
      Glatzel/G-Rhino
      Glatzel/jxws
      Glatzel/knitting
      Glatzel/py-glatzel
      Glatzel/xm-metro-qr
      Glatzel/watch-media
      Glatzel/zygs
      