name: cache-pixi
on:
  workflow_call:
    inputs:
      machine:
        type: string
        required: true
      pixi_env:
        type: string
        required: true

jobs:
  cache-pixi:
    runs-on: ${{inputs.machine}}
    steps:
      - uses: actions/checkout@v4

      - name: check-cache
        uses: actions/cache/restore@v4
        id: check-cache
        with:
          path: .pixi
          key: pixi-${{inputs.pixi_env}}-${{ runner.os }}-${{ hashFiles('**/pixi.lock') }}
          lookup-only: true

      - name: Set up pixi
        if: ${{! steps.check-cache.outputs.cache-hit}}
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          run-install: false

      - name: pixi install
        if: ${{! steps.check-cache.outputs.cache-hit}}
        run: pixi install -e ${{inputs.pixi_env}}

      - name: Save pixi cache
        if: ${{! steps.check-cache.outputs.cache-hit}}
        uses: actions/cache/save@v4
        with:
          path: .pixi
          key: ${{steps.check-cache.outputs.cache-primary-key}}
