name: cache-pixi
on:
  workflow_call:
    inputs:
      machine:
        type: string
        required: true
      envs:
        type: string
        required: true

jobs:
  cache-pixi:
    runs-on: ${{inputs.machine}}
    steps:
      - uses: actions/checkout@v4

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          environments: ${{inputs.envs}}
          cache-key: pixi-${{runner.os}}-