name: cache-pixi
on:
  workflow_call:
    inputs:
      machine:
        type: string
        required: true
      install_cmd:
        type: string
        default: pixi install --all

jobs:
  cache-pixi:
    runs-on: ${{inputs.machine}}
    steps:
      - uses: actions/checkout@v4

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          run-install: false

      - name: create cache
        run: ${{inputs.install_cmd}}

      - name: Save pixi cache
        if: ${{runner.os == 'windows'}}
        uses: actions/cache/save@v4
        with:
          path: .pixi
          key: pixi-${{ runner.os }}-${{ hashFiles('**/pixi.lock') }}
