name: cache-pixi
on:
  workflow_call:
    inputs:
      machine:
        type: string
        required: true
      install_cmd:
        type: string
        default: pixi install --all

jobs:
  cache-pixi:
    runs-on: ${{inputs.machine}}
    steps:
      - uses: actions/checkout@v4

      - name: check-cache
        uses: actions/cache@v4
        id: check-cache
        with:
          path: .pixi
          key: pixi-${{ runner.os }}-${{ hashFiles('**/pixi.lock') }}

      - name: Set up pixi
        if: ${{! steps.check-cache.outputs.cache-hit}}
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          run-install: false

      - name: create cache
        if: ${{! steps.check-cache.outputs.cache-hit}}
        run: ${{inputs.install_cmd}}

