name: release changelog

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
      output_name:
        type: string
        default: changelog

jobs:
  release-body:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: add tag
        run: |
          git tag ${{inputs.tag}}
          git push origin --tags
        continue-on-error: true
      
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          run-install: false

      - name: Generate a changelog
        run: |
          pixi global install git-cliff
          git-cliff --tag ${{inputs.tag}} > ${{inputs.output_name}}.md

      - uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: ${{inputs.output_name}}.md
          if-no-files-found: error