name: release

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
      output_file:
        type: string
        default: current_changelog.md

jobs:
  add-tag:
    env:
      IS_PRE_RELEASE:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: is-pre-release
        run: |
          if("${{inputs.tag}}" -match '^v\d+\.\d+\.\d$' ){"IS_PRE_RELEASE=false" >> "$env:GITHUB_ENV"}
          elseif("${{inputs.tag}}" -match '^v\d+\.\d+\.\d-.*$') {"IS_PRE_RELEASE=true" >> "$env:GITHUB_ENV"}
          else{throw "Unknown version: '${{inputs.tag}}'"}

      - name: add tag
        run: |
          git tag ${{inputs.tag}}
          git push origin --tags
        continue-on-error: true

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          run-install: false

      - name: release-body
        run: |
          pixi global install git-cliff
          git-cliff --unreleased --tag ${{inputs.tag}} --strip header
          if($env:IS_PRE_RELEASE -eq "true"){git-cliff --unreleased --tag ${{inputs.tag}} --strip header > release_body.md}
          else{git-cliff --tag ${{inputs.tag}} --strip header > release_body.md}

      - uses: actions/upload-artifact@v4
        with:
          name: release-body
          path: ./${{inputs.output_file}}
          if-no-files-found: error