name: release

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
      is_pre_release:
        type: boolean
        required: true
      output_file:
        type: string
        default: current_changelog.md

jobs:
  release-body:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate a changelog (release)
        if: ${{inputs.is_pre_release == 'false'}}
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: ${{inputs.output_file}}
          GITHUB_REPO: ${{ github.repository }}
      
      - name: Generate a changelog (pre-release)
        if: ${{inputs.is_pre_release == 'true'}}
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --verbose --unreleased --tag ${{inputs.tag}} --strip header
        env:
          OUTPUT: release_body.md
          GITHUB_REPO: ${{ github.repository }}
        
      - uses: actions/upload-artifact@v4
        with:
          name: release-body
          path: ${{inputs.output_file}}
          if-no-files-found: error