name: coverage
on:
  workflow_call:
    inputs:
        machine:
          type: string
          required: true
        cov_thr:
          type: number
          default: 70
jobs:
    coverage:
        name: Coverage Summary
        runs-on: ubuntu-24.04
        steps:
          - uses: actions/checkout@v4

          - name: Set up pixi
            uses: prefix-dev/setup-pixi@v0.8.1
            with:
              run-install: false

          - name: Install coverage
            run: pip global install coverage

          - name: Download data
            uses: actions/download-artifact@v4
            with:
              path: ${{ github.workspace }}
              pattern: coverage-data-*
              merge-multiple: true

          - name: Combine coverage and check cover
            run: |
              coverage combine
              coverage html --skip-covered --skip-empty
              coverage report --fail-under=${{inputs.cov_thr}}
              coverage report --format=markdown >> $GITHUB_STEP_SUMMARY

          - name: Upload HTML report
            if: ${{ failure() }}
            uses: actions/upload-artifact@v4
            with:
              name: html-report
              path: htmlcov