name: coverage
on:
  workflow_call:
    inputs:
        machine:
          type: string
          required: true
        cov_thr:
          type: number
          default: 100
jobs:
    coverage:
        name: Coverage Summary
        runs-on: ${{inputs.machine}}
        steps:
          - uses: actions/checkout@v4

          - name: Set up pixi
            uses: prefix-dev/setup-pixi@v0.8.1
            with:
              run-install: false

          - name: Install coverage
            run: pixi global install coverage

          - name: Download data
            uses: actions/download-artifact@v4
            with:
              path: ${{ github.workspace }}
              pattern: coverage-data-${{inputs.machine}}-*
              merge-multiple: true

          - name: Combine coverage and check cover
            if: runner.os == 'Windows'
            run: |
              coverage combine
              coverage html --skip-covered --skip-empty
              
              "## Coverage Summary (Windows)" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
              coverage report --format=markdown | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
              coverage report --fail-under=${{inputs.cov_thr}}

          - name: Upload HTML report
            if: ${{ failure() }}
            uses: actions/upload-artifact@v4
            with:
              name: html-report
              path: htmlcov