name: lint
on:
  workflow_call:
    inputs:
      codecov:
        description: Whether to use codecov.
        type: boolean
        default: false
    secrets:
      CODECOV_TOKEN:
        required: false
    
jobs:
  ruff-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          run-install: false

      - name: install ruff
        run: |
          pixi global install ruff

      - name: lint
        run: |
          # ruff check --output-format=github .
            ruff check --output-format=junit . > junit.xml
      
      - name: Upload test results to Codecov
        if: ${{inputs.codecov&&!cancelled()}}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}