on:
  workflow_call:
    inputs:
      machine:
        type: string
        required: true

jobs:
  ruff-lint:
    runs-on: ${{inputs.machine}}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          run-install: false

      - name: install ruff
        run: |
          pixi global install ruff

      - name: lint(windows)
        if: runner.os == 'Windows'
        run: |
          ruff check --output-format=junit . >> lint.xml

      - name: lint(linux)
        if: runner.os == 'Linux'
        run: |
          ruff check --output-format=junit . >> lint.xml
            - name: Test Report title

      - name: Lint Report
        uses: dorny/test-reporter@main
        if: success() || failure()
        with:
          name: Lint Report
          path: lint.xml
          reporter: jest-junit
          use-actions-summary: "true"