name: pytest

on:
    workflow_call:
      inputs:
        machine:
          required: true
          type: string
        test_path:
          default: ./tests
          type: string
        python_path:
          type: string
          default: ""
        pixi_python_env:
            type: string
            default: default
        test_arg:
          type: string
          default: ""
jobs:
  pytest:
    runs-on: ${{inputs.machine}}
    steps:
      - uses: actions/checkout@v4

      - name: Update Submodule
        run: git submodule update --init --recursive

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          run-install: false

      - name: pytest
        if: runner.os == 'Windows' && success()
        run: |
          $Env:PYTHONPATH = "${{inputs.python_path}}" 
          pixi run -e ${{inputs.pixi_python_env}} pytest "${{inputs.test_path}}" ${{inputs.test_arg}}
