name: pytest

on:
    workflow_call:
      inputs:
        name:
          required: true
          type: string
        machine:
          required: true
          type: string
        submodule:
          type: boolean
          default: false
        test_path:
          default: ./tests
          type: string
        python_path:
          type: string
          default: ""
        pixi_python_env:
            type: string
            default: default
        test_args:
          type: string
          default: ""
        cov_name:
          type: string
          default : ""
        cov_args:
          type: string
          default : ""
        cov_thr:
          type: number
          default: 100
        
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  pytest:
    runs-on: ${{inputs.machine}}
    steps:
      - uses: actions/checkout@v4

      - name: Update Submodule
        if: ${{inputs.submodule}}
        run: git submodule update --init --recursive

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          run-install: false

      - name: pytest
        if: runner.os == 'Windows' && success()
        run: |
          $Env:PYTHONPATH = "${{inputs.python_path}}"
          pixi run -e ${{inputs.pixi_python_env}} pytest "${{inputs.test_path}}" --junit-xml results/pytest.xml ${{inputs.cov_args}} ${{inputs.test_args}}
      - name: Test Report Title
        run: |
          "## Test Report"| Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append

      - name: Test Report
        uses: dorny/test-reporter@main
        if: success() || failure()    
        with:
          name: Pytest Report (${{inputs.name}})
          path: results/pytest.xml
          reporter: java-junit
          use-actions-summary: "true"

      - name: Coverage Summary
        if: ${{inputs.cov_name == inputs.name}} && (success() || failure())
        run: |
          pixi global install coverage
          "## Coverage Summary"| Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          coverage report --fail-under=${{inputs.cov_thr}} --format=markdown | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
