name: pytest

on:
    workflow_call:
      inputs:
        machine:
          default: ubuntu-latest
          type: string
        test_path:
          default: ./tests
          type: string
        python_path:
          default: $PYTHONPATH
          type: string
jobs:
  pytest:
    runs-on: ${{inputs.machine}}
    steps:
      - uses: actions/checkout@v4

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          run-install: false

      - name: pytest
        run: |
          pixi run pytest "${{inputs.test_path}}"
        shell: pwsh