permissions: 
  contents: write
  pull-requests: write

on:
  workflow_call:

jobs:
  sync-python-template:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clone templete
        run: |
          git clone https://github.com/Glatzel/py-template.git temp
      
      - name: Copy files
        if: ${{ success() }}
        run: |
          New-Item ./scripts -ItemType Directory -ErrorAction SilentlyContinue
          Copy-Item ./temp/template/scripts/* ./scripts
          Copy-Item ./temp/template/ruff.toml ./ruff.toml
          Remove-Item ./temp -Recurse -Force

      - name: Create pull request
        if: ${{ success() }}
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Sync template files
          title: Sync template files
          branch: sync-template-files
          base: main
          labels: Action
          delete-branch: true
          assignees: Glatzel
