name: Update lockfiles

permissions: 
  contents: write
  pull-requests: write

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pixi-update:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          run-install: false

      - name: Install pixi-diff-to-markdown
        if: ${{ success() }}
        run: pixi global install pixi-diff-to-markdown

      - name: Update lockfiles
        if: ${{ success() }}
        run: pixi update --json | pixi exec pixi-diff-to-markdown >> diff.md

      - name: Create pull request
        if: ${{ success() }}
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update pixi lockfile
          title: "chore: update pixi lockfile"
          body-path: diff.md
          branch: update-pixi
          base: main
          labels: action
          delete-branch: true
          add-paths: pixi.lock
          assignees: Glatzel
